name: Install test
on: [push]
jobs:
  install-18:
    container:
      image: "ubuntu:18.04"
    # runs-on: ubuntu-latest
    steps:
      - run: echo "🐧 Running on ${{ runner.os }}!"
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: ./piku-bootstrap first-run --no-interactive
      - run: cd ~/.piku-bootstrap/piku-bootstrap && git checkout ${{ github.event.pull_request.head.sha }}
      - run: ./piku-bootstrap install

