name: Install test
on: [push]
jobs:
  piku-bootstrap-install:
    runs-on: ubuntu-latest
    env:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    strategy:
      matrix:
        version: ["ubuntu:22.04", "ubuntu:20.04", "ubuntu:18.04"]
    container:
      image: ${{ matrix.version }}
    steps:
      - run: echo "🐧 Running on ${{ runner.os }}!"
      - run: cat /etc/lsb-release
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: ./piku-bootstrap first-run --no-interactive
      - run: cd ~/.piku-bootstrap/piku-bootstrap && git checkout $GITHUB_SHA
      - run: ./piku-bootstrap install

